name: Update Weather Data

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every hour

jobs:
  update_weather_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python getData_1h.py
        python mongoDB.py